# Site settings
title: Cemosis
email: contact@cemosis.fr
description: > # this means to ignore newlines until "baseurl:"
              Cemosis, le Centre de Modélisation et de Simulation de Strasbourg, est une structure à
              l'interface avec les disciplines  et les entreprises nécessitant la modélisation et la
              simulation numérique.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cemosis.fr/" # the base hostname & protocol for your site
twitter_username:
github_username: 

# Build settings
markdown: kramdown

highlighter: pygments